spring:
  application:
    name: groupup
  profiles:
    active: safety-nonpublic-dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 7011