spring:
  application:
    name: groupup
  profiles:
    active: prod
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  auth-enable: true
  secret: secret12740184018403rujdfcu9hv9nsdzsajsz0ehfUO(vhqoCQfsecret12740184018403rujdfcu9hv9nsdzsajsz0ehfUO(vhqoCQf
  expiration: 86400000

